Module3 task1
htmlacademy-adaptive/1247033-pink-20 pull request #5
Opened 2020-09-14 02:07 UTC by EnjoyTWOS

2020-09-14 16:34 UTC, DoberBober commented on source/contest.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
Все шрифты должны быть подключены локально. Google Fonts не допускается.

2020-09-14 16:35 UTC, DoberBober commented on source/less/blocks/advantages.less
> +  .text-light;
Тут скобки должны быть?

2020-09-14 16:36 UTC, DoberBober commented on source/less/blocks/advantages.less
> +  .list-style;
list-style: none?

2020-09-14 16:36 UTC, DoberBober commented on source/less/blocks/contest-promo.less
> +  .text-light;
Тоже не понял что за селекторы.

2020-09-14 16:36 UTC, DoberBober commented on source/less/blocks/download.less
> +  .center-white;
?

2020-09-14 16:36 UTC, DoberBober commented on source/less/blocks/download.less
> +  .list-style;
?

2020-09-14 16:36 UTC, DoberBober commented on source/less/blocks/download.less
> +  .center-white;
?

2020-09-14 16:37 UTC, DoberBober commented on source/less/mixins.less
> +.list-style {
Это ж не миксины.

2020-09-14 16:37 UTC, DoberBober commented on source/less/blocks/photos__list.less
> +.photos__item img {
Этот файл не должен быть. Стилевые файлы создаёшь только для блоков.

2020-09-14 16:38 UTC, DoberBober requested changes
Во многих местах стили лежат не в своих файлах. Например, файл называется page-footer.less, а внутри лежат стили для social__list и copyright__text.
Плюс во многих местах просто перечислены селекторы рядом с CSS-свойствами.

2020-09-14 17:03 UTC, EnjoyTWOS commented on source/less/mixins.less
> +.list-style {
![mixin](https://user-images.githubusercontent.com/58084799/93116000-5d264200-f6c5-11ea-89eb-d3e31b8e92f1.jpg)
Почему это не примеси?

2020-09-14 17:11 UTC, DoberBober commented on source/less/mixins.less
> +.list-style {
Ой, блин. Прошу прощения, под вечер голова не думает. Я почему-то решил, что ты на sass-е сидишь. Соответственно, ошибки, в которых писал ,что у тебя селекторы просто в списке стилей тоже снимаются.

2020-09-14 18:24 UTC, DoberBober commented
Стили в свои файлы не раскидал же.
![image](https://user-images.githubusercontent.com/18398812/93123373-a4fe9680-f6d0-11ea-9215-891ee8d146b8.png)

2020-09-14 21:10 UTC, EnjoyTWOS commented
> Стили в свои файлы не раскидал же.
> ![image](https://user-images.githubusercontent.com/18398812/93123373-a4fe9680-f6d0-11ea-9215-891ee8d146b8.png)

![site-list](https://user-images.githubusercontent.com/58084799/93138520-ccad2900-f6e7-11ea-9593-c795682e402c.jpg)
![social](https://user-images.githubusercontent.com/58084799/93138525-d171dd00-f6e7-11ea-9d64-b18c24b9ac90.jpg)
так раскидал же сразу

2020-09-15 09:27 UTC, DoberBober commented
Ты вчера не запушил, видимо. Теперь вижу коммит.

2020-09-15 09:27 UTC, merged